include: package:pedantic/analysis_options.yaml # https://pub.dartlang.org/packages/pedantic
analyzer: 
  exclude: 
    - example/**
linter: # Lint rules: http://dart-lang.github.io/linter/lints/
  rules:
    - avoid_empty_else # https://dart-lang.github.io/linter/lints/avoid_empty_else.html
    - avoid_relative_lib_imports # https://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html
    - avoid_slow_async_io # https://dart-lang.github.io/linter/lints/avoid_slow_async_io.html
    - avoid_types_as_parameter_names # https://dart-lang.github.io/linter/lints/avoid_types_as_parameter_names.html
    - cancel_subscriptions # https://dart-lang.github.io/linter/lints/cancel_subscriptions.html
    - close_sinks # https://dart-lang.github.io/linter/lints/close_sinks.html
    - control_flow_in_finally # https://dart-lang.github.io/linter/lints/control_flow_in_finally.html
    - hash_and_equals # http://dart-lang.github.io/linter/lints/hash_and_equals.html
    - iterable_contains_unrelated_type # http://dart-lang.github.io/linter/lints/iterable_contains_unrelated_type.html
    - list_remove_unrelated_type # http://dart-lang.github.io/linter/lints/list_remove_unrelated_type.html
    - literal_only_boolean_expressions # http://dart-lang.github.io/linter/lints/literal_only_boolean_expressions.html
    - no_adjacent_strings_in_list # http://dart-lang.github.io/linter/lints/no_adjacent_strings_in_list.html
    - unawaited_futures # https://dart-lang.github.io/linter/lints/unawaited_futures.html
    - unnecessary_statements # http://dart-lang.github.io/linter/lints/unnecessary_statements.html
    - unrelated_type_equality_checks # https://dart-lang.github.io/linter/lints/unrelated_type_equality_checks.html
    - valid_regexps # https://dart-lang.github.io/linter/lints/valid_regexps.html